apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: color
  name: color
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
      - image: haugom/color:sha-864e1b4
        name: color
        ports:
          - name: http
            containerPort: 8081
            protocol: TCP

