apiVersion: apps/v1
kind: Deployment
metadata:
  name: color
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: color
          envFrom:
            - configMapRef:
                name: config

