apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: blue-
commonLabels:
  variant: blue

resources:
  - ../color

configMapGenerator:
  - name: config
    literals:
      - COLOR=blue
      - BACKEND=http://blue-color-backend.haugom.svc/data

patchesStrategicMerge:
  - deployment.yaml
