apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: blue-

resources:
  - ../color

configMapGenerator:
  - literals:
      - COLOR=blue
      - BACKEND=http://blue-color-backend.haugom.svc/data
    name: config

labels:
  - includeSelectors: true
    pairs:
      variant: blue
patches:
  - path: deployment.yaml
