---
- hosts: minion
  become: yes
  roles:
    - role: gantsign.golang
      golang_gopath: '$HOME/workspace-go'
    - { name: roles/helm }
    - { name: roles/cks }
    - { name: roles/containerd }
#    - { name: roles/crio }

