---
- hosts: kubernetes2
  become: yes
  roles:
    - { name: roles/cks }
    - { name: roles/crio }
    - role: gantsign.golang
      golang_gopath: '$HOME/workspace-go'

- hosts: kubernetes2
  become: yes
  roles:
    - { name: roles/helm }
