apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "configure ingress"
  name: ingress2
spec:
  appliesToWorkloads:
    - webservice
  schematic:
    cue:
      template: |
