apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: nginx:1.21
        port: 80
      traits:
        - type: ingress2
          properties:
            domain: testsvc.lab.cloud.haugom.org
            http:
              "/": 80
