apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-red-backend
  namespace: system
spec:
  podSelector:
    matchLabels:
      app: color
      variant: red-color-backend
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-red-frontend
  namespace: system
spec:
  podSelector:
    matchLabels:
      app: color
      variant: red-color-backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: color
              variant: red
