apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: red-
nameSuffix: -backend

commonLabels:
  variant: red-color-backend

resources:
  - ../color

configMapGenerator:
  - name: config
    literals:
      - COLOR=red
      - DATA=red-backend

patchesStrategicMerge:
  - deployment.yaml
