apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: red-
nameSuffix: -backend


resources:
  - ../color

configMapGenerator:
  - literals:
      - COLOR=red
      - DATA=red-backend
    name: config

labels:
  - includeSelectors: true
    pairs:
      variant: red-color-backend
patches:
  - path: deployment.yaml
