apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  - "RequestReceived"
rules:
  - level: RequestResponse
    resources:
      - group: ""
        resources:
          - "pods"
  - level: Metadata
    resources:
      - group: ""
        resources:
          - "pods/log"
          - "pods/status"
  - level: Metadata
    userGroups:
      - "system:authenticated"
    nonResourceURLs:
      - "/api*"
      - "/version"
  - level: Request
    resources:
      - group: ""
        resources:
          - "configmaps"
    namespaces:
      - "kube-system"
  - level: Metadata
    resources:
      - group: ""
        resources:
          - "secrets"
          - "configmaps"
    omitStages:
      - "RequestReceived"

