apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: blue-
nameSuffix: -backend


resources:
  - ../color

configMapGenerator:
  - literals:
      - COLOR=blue
      - DATA=blue-backend
    name: config

labels:
  - includeSelectors: true
    pairs:
      variant: blue-color-backend
patches:
  - path: deployment.yaml
