apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: blue-
nameSuffix: -backend

commonLabels:
  variant: blue-color-backend

resources:
  - ../color

configMapGenerator:
  - name: config
    literals:
      - COLOR=blue
      - DATA=blue-backend

patchesStrategicMerge:
  - deployment.yaml
