apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-access-cr
subjects:
- kind: ServiceAccount
  name: secret-access-sa
  namespace: default
