apiVersion: v1
kind: Service
metadata:
  labels:
    app: second
  name: second
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: second
status:
  loadBalancer: {}
