apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: red-

resources:
  - ../color

configMapGenerator:
  - literals:
      - COLOR=red
      - BACKEND=http://red-color-backend.haugom.svc/data
    name: config

labels:
  - includeSelectors: true
    pairs:
      variant: red
patches:
  - path: deployment.yaml
