apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: red-
commonLabels:
  variant: red

resources:
  - ../color

configMapGenerator:
  - name: config
    literals:
      - COLOR=red
      - BACKEND=http://red-color-backend.haugom.svc/data

patchesStrategicMerge:
  - deployment.yaml
