apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: do-issuer
spec:
  acme:
    email: www@haugom.org
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-dns
              key: digitalocean_api_token
