---
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Disable swap for current session
  command: swapoff -a
  become: true
  changed_when: False

- name: Disable swap permanently, persist reboots
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: yes

- name: "Mobprobe the {{ item }} module"
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

# https://packages.cloud.google.com/apt/doc/apt-key.gpg
- name: kubernetes apt key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    state: present

- name: docker apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: Template a file to /etc/apt/sources.list.d/kubernetes.list
  ansible.builtin.template:
    src: kubernetes.sources.j2
    dest: /etc/apt/sources.list.d/kubernetes.list
    mode: '0644'

- name: Template a file to /etc/apt/sources.list.d/docker.list
  ansible.builtin.template:
    src: docker.sources.j2
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0644'

- name: set ip_forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: set vm.max_map_count
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '262144'
    sysctl_set: yes
    state: present
    reload: yes

- name: Prevent kubeadm from upgrading
  ansible.builtin.dpkg_selections:
    name: kubeadm
    selection: install
- name: Prevent kubelet from upgrading
  ansible.builtin.dpkg_selections:
    name: kubelet
    selection: install
- name: Prevent kubectl from upgrading
  ansible.builtin.dpkg_selections:
    name: kubectl
    selection: install

- name: "Install yq {{ yq_version }}"
  get_url:
    url: "https://github.com/mikefarah/yq/releases/download/{{ yq_version }}/yq_linux_amd64"
    dest: /usr/local/bin/yq
    mode: 'u=rx,g=rx,o=rx'

- name: Install a list of packages
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
      - lsb-release
      - kubelet={{ kubernetes_version }}-00
      - kubeadm={{ kubernetes_version }}-00
      - kubectl={{ kubernetes_version }}-00
      - bash-completion
      - jq

- name: Prevent kubeadm from upgrading
  ansible.builtin.dpkg_selections:
    name: kubeadm
    selection: hold
- name: Prevent kubelet from upgrading
  ansible.builtin.dpkg_selections:
    name: kubelet
    selection: hold
- name: Prevent kubectl from upgrading
  ansible.builtin.dpkg_selections:
    name: kubectl
    selection: hold

- name: Create a symbolic link
  ansible.builtin.file:
    src: /usr/bin/kubectl
    dest: /usr/bin/k
    state: link

- name: Generate /etc/hosts file
  ansible.builtin.template:
    src=hosts.j2
    dest=/etc/hosts

- name: Download calico.yaml
  get_url:
    url: https://docs.projectcalico.org/manifests/calico.yaml
    dest: /home/haugom/calico.yaml
    mode: '0444'

- name: Template a file to /etc/profile.d/
  ansible.builtin.template:
    src: profile_kubectl.j2
    dest: /etc/profile.d/kubectl.sh
    mode: '0644'
