apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:super
rules:
  - apiGroups:
      - policy
    resourceNames:
      - super
    resources:
      - podsecuritypolicies
    verbs:
      - use
