apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: green-
nameSuffix: -backend


resources:
  - ../color

configMapGenerator:
  - literals:
      - COLOR=green
      - DATA=green-backend
    name: config

labels:
  - includeSelectors: true
    pairs:
      variant: green-color-backend
patches:
  - path: deployment.yaml
