apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: green-
nameSuffix: -backend

commonLabels:
  variant: green-color-backend

resources:
  - ../color

configMapGenerator:
  - name: config
    literals:
      - COLOR=green
      - DATA=green-backend

patchesStrategicMerge:
  - deployment.yaml
