apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app
  name: app
spec:
  containers:
  - image: busybox
    name: app
    command: ["/bin/sh"]
    args: 
      - -c
      - |
        while true; do echo "$(date) | $(du -sh ~)" >> /var/logs/diskspace.txt; sleep 5; done;
    resources: {}
    volumeMounts:
      - name: logs
        mountPath: /var/logs
  - image: busybox
    name: transformer
    command: ["/bin/sh"]
    args: 
      - -c
      - |
        cd /var/logs
        sleep 20; while true; do while read LINE; do echo "$LINE" | cut -f2 -d"|" >> $(date +%Y-%m-%d-%H-%M-%S)-transformed.txt; done < /var/logs/diskspace.txt; sleep 20; done;
    resources: {}
    volumeMounts:
      - name: logs
        mountPath: /var/logs
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: logs
      emptyDir: {}
status: {}
