apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert 
  namespace: haugom
spec:
  dnsNames:
    - nginx.lab.cloud.haugom.org
  secretName: lab-cert-tls
  issuerRef:
    name: letsencrypt-prod
