apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert 
spec:
  dnsNames:
    - grafana.lab.cloud.haugom.org
  secretName: grafana-cert-tls
  issuerRef:
    name: letsencrypt-prod
