apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-two
  namespace: student
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      system: DaemonSetTwo
  template:
    metadata:
      creationTimestamp: null
      labels:
        system: DaemonSetTwo
    spec:
      containers:
      - image: nginx:1.15.1
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
