apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: two
  namespace: accounting
spec:
  rules:
    - host: two.accounting.svc.cluster.local
      http:
        paths:
          - backend:
              service:
                name: nginx-two
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
