apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab5
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/sfw
    server: gha-worker-0
    readOnly: false
