apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-one
  labels:
    system: secondary
  namespace: accounting
spec:
  selector:
    matchLabels:
      system: secondary
  replicas: 2
  template:
    metadata:
      labels:
        system: secondary
    spec:
      runtimeClassName: gvisor
      containers:
        - name: nginx
          image: nginx:1.20.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP

