apiVersion: batch/v1
kind: Job
metadata:
  annotations:
  name: sleepy
  namespace: student
spec:
  backoffLimit: 6
  completions: 5
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - args:
        - "3"
        command:
        - /bin/sleep
        image: busybox
        imagePullPolicy: Always
        name: sleepy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
