apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: green-
commonLabels:
  variant: green

resources:
  - ../color

configMapGenerator:
  - name: config
    literals:
      - COLOR=green
      - BACKEND-old=http://green-color-backend.haugom.svc/data
      - BACKEND=https://color.k8s.cloud.haugom.org/data
      - BACKENDx=https://haugom.org

patchesStrategicMerge:
  - deployment.yaml
