apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: green-in-cluster-

resources:
  - ../color

configMapGenerator:
  - literals:
      - COLOR=green
      - BACKEND=http://green-color-backend.haugom.svc/data
      - BACKENDy=https://color.k8s.cloud.haugom.org/data
      - BACKENDx=https://haugom.org
    name: config

labels:
  - includeSelectors: true
    pairs:
      variant: green-in-cluster
patches:
  - path: deployment.yaml
