---
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

# https://packages.cloud.google.com/apt/doc/apt-key.gpg
- name: kubernetes apt key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    state: present

- name: docker apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: crio key
  ansible.builtin.apt_key:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}/{{ crio_os }}/Release.key
    keyring: /usr/share/keyrings/crio-keyring.gpg
    state: present

- name: libcontainers key
  ansible.builtin.apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ crio_os }}/Release.key
    keyring: /usr/share/keyrings/crio-keyring.gpg
    state: present

#- name: Print all available facts
#  ansible.builtin.debug:
#    var: ansible_facts

- name: Template a file to /etc/apt/sources.list.d/kubernetes.list
  ansible.builtin.template:
    src: kubernetes.sources.j2
    dest: /etc/apt/sources.list.d/kubernetes.list
    mode: '0600'

- name: Template a file to /etc/apt/sources.list.d/crio.list
  ansible.builtin.template:
    src: crio-list.j2
    dest: /etc/apt/sources.list.d/crio.list
    mode: '0600'
- name: Template a file to /etc/apt/sources.list.d/libcontainers-stable.list
  ansible.builtin.template:
    src: libcontainers-stable.j2
    dest: /etc/apt/sources.list.d/libcontainers-stable.list
    mode: '0600'

- name: Create directory if it does not exist /etc/containers/
  ansible.builtin.file:
    path: /etc/containers
    state: directory
    mode: '0755'

- name: Template a file to /etc/containers/registries.conf
  ansible.builtin.template:
    src: crio.registries.conf.j2
    dest: /etc/containers/registries.conf
    mode: '0600'

- name: Template a file to /etc/apt/sources.list.d/docker.list
  ansible.builtin.template:
    src: docker.sources.j2
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0600'

- name: Template a file to /etc/modules-load.d/k8s.conf
  ansible.builtin.template:
    src: k8s-modules.conf.j2
    dest: /etc/modules-load.d/k8s.conf
    mode: '0600'
  register: result1

- name: Template a file to /etc/sysctl.d/k8s.conf
  ansible.builtin.template:
    src: k8s-sysctl.conf.j2
    dest: /etc/sysctl.d/k8s.conf
    mode: '0600'
  register: result2


- name: sysctl --system
  shell: sysctl -p --system
  when: result1.changed or result2.changed

- name: set ip_forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: set vm.max_map_count
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '262144'
    sysctl_set: yes
    state: present
    reload: yes

- name: Install a list of packages
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - kubelet={{ kubernetes_version }}-00
      - kubeadm={{ kubernetes_version }}-00
      - kubectl={{ kubernetes_version }}-00
      - docker-ce-cli
      - cri-o
      - cri-o-runc
      - bash-completion

- name: Prevent kubeadm from upgrading
  ansible.builtin.dpkg_selections:
    name: kubeadm
    selection: hold
- name: Prevent kubelet from upgrading
  ansible.builtin.dpkg_selections:
    name: kubelet
    selection: hold
- name: Prevent kubectl from upgrading
  ansible.builtin.dpkg_selections:
    name: kubectl
    selection: hold

- name: Ensure conmon is set
  ansible.builtin.lineinfile:
    path: /etc/crio/crio.conf
    regexp: '^conmon = "/usr/libexec/crio/conmon"'
    line: conmon = "/usr/bin/conmon"

- name: Just force systemd to reread configs (2.4 and above)
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable service crio
  ansible.builtin.service:
    name: crio
    enabled: yes
    state: started

- name: Generate /etc/hosts file
  ansible.builtin.template:
    src=hosts.j2
    dest=/etc/hosts
