datadog:
  site: datadoghq.eu
#  apiKeyExistingSecret: datadog

  logs:
    enabled: true
    containerCollectAll: true

  kubelet:
    tlsVerify: false

  containers:
    agent:
      ## @param env - list - required
      ## Additional environment variables for the agent container.
      #
      env:
        - name: DD_KUBELET_TLS_VERIFY
          value: "false"

  ignoreAutoConfig:
    - etcd
  confd:
    etcd.yaml: |-
      ad_identifiers:
        - etcd
      instances:
        - prometheus_url: https://%%host%%:2379/metrics
          tls_ca_cert: /host/etc/kubernetes/pki/etcd/ca.crt
          tls_cert: /host/etc/kubernetes/pki/etcd/server.crt
          tls_private_key: /host/etc/kubernetes/pki/etcd/server.key
    kubernetes-audit-log: |-
      logs:
        - type: file
          path: /etc/kubernetes/audit-log/audit.log
          source: kubernetes.audit
          service: audit
agents:
  volumes:
    - hostPath:
        path: /etc/kubernetes/pki/etcd
      name: etcd-certs
    - hostPath:
        path: /etc/kubernetes/audit-log
        type: DirectoryOrCreate
      name: auditdir
  volumeMounts:
    - name: etcd-certs
      mountPath: /host/etc/kubernetes/pki/etcd
      readOnly: true
    - name: auditdir
      mountPath: /etc/kubernetes/audit-log
      readOnly: true
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
